# Site settings
title: "OpenReferral Workshop - July 2014"
email: ""
description: ""
baseurl: "http://eric-jahn.github.io/workshop/"
url: ""
safe: true
lsi: false

# Build settings
markdown: kramdown
permalink: pretty
